### ISSUE TITLE
Update readme section for languages and techniques

### ISSUE THREAD

**Issue by immaroot** [DGovi/Rogue#13]
TBD

**Comment by immaroot** [comment]
Laravel (PHP)
SQL
HTML
CSS
SASS?

**Comment by j-eltayar** [comment]
Yes as well as React for JS would there be any others missing?

**Comment by DGovi** [comment]
I think it's good enough for now. We can update if anything changes.

**Comment by DGovi** [comment]
Can we close this issue?
