### ISSUE TITLE
Change the content of the "Edit Profile" page

### ISSUE THREAD

**Issue by SekayZ** [DGovi/Rogue#40]
- Story points : 3
 - Priority : high
 - Risk : high

Story points, priority and risk has been concluded by planning poker on Feb 24th.

Edit to be able to: 
 - change username

**Comment by SekayZ** [comment]
added the change "Name" box

**Comment by SekayZ** [comment]
completed the front-end part

**Comment by immaroot** [comment]
Edit page should contain:
 - Change Profile Pic
 - Change Bio
 - Change Username
 - Modify Email
