### ISSUE TITLE
Testing the core features

### ISSUE THREAD

**Issue by SekayZ** [DGovi/Rogue#52]
Document some testing for all the core features

**Comment by immaroot** [comment]
I have added the following tests in tests/Unit/UserTest.php in the branch testing:
 - test_as_a_guest_I_can_register()
 - test_as_a_user_I_can_login()
 - test_as_a_user_I_can_create_a_post()
 - test_as_a_user_I_can_follow_someone_else()
 - test_as_a_user_I_can_comment_on_someone_elses_post()
