### ISSUE TITLE
Create a Feed Page of which user is following (Home\Rogue button) 

### ISSUE THREAD

**Issue by immaroot** [DGovi/Rogue#61]
- Story points : 3
 - Priority : high
 - Risk : low

Story points, priority and risk has been concluded by planning poker on Feb 24th.

Page that displays all posts from users the user is following by chronological order. (ei.: newest first)

**Comment by immaroot** [comment]
related to user story - issue #58

**Comment by DGovi** [comment]
sorry closed the wrong one
