### ISSUE TITLE
When pressing on followers or following display list

### ISSUE THREAD

**Issue by immaroot** [DGovi/Rogue#75]
- Story points: 13
 - Priority: low
 - Risk: low

Story points, priority and risk has been concluded by planning poker on Mar 25th.

On any profile page where it shows the number of followers and followings, let the user see a list of them.

**Comment by immaroot** [comment]
Working version on branch issue/#75

**Comment by immaroot** [comment]
pull request made to close issue

**Comment by DGovi** [comment]
good work killian
