### ISSUE TITLE
Fix a size for uploaded images

### ISSUE THREAD

**Issue by immaroot** [DGovi/Rogue#77]
- Story points: 3
 - Priority: low
 - Risk: low

Story points, priority and risk has been concluded by planning poker on Mar 25th.

Fix a square size for an image to post. Should be done on server side and saved only in format wanted.

**Comment by SekayZ** [comment]
Used the intervention image package to resize the image

**Comment by immaroot** [comment]
There is no branch our commit on this issue. Please leave it open until the functionality is inplemented.

**Comment by immaroot** [comment]
I agree using the image intervention would be an ideal choice. 

http://image.intervention.io/
